--?? Beginner — SELECT, WHERE, ORDER BY
--Display the first 20 records from the Orders table.
select top 20 * from orders

--Find all customers from the South region.
select * from customers 

select * from customers 
where region ='south'


--Find products with a list_price greater than ?10,000.

select * from products 

select *from products 
where list_price >10000

--Find orders where the quantity is greater than 3.
select *from orders 

select * from orders 
where quantity>3

--Find all orders that were cancelled.
select * from orders 
where order_status='cancelled'


--Find customers whose age is between 25 and 40.
select *from customers 

select * from customers 
where age between 25 and 40


--Find products belonging to the Electronics category.
select *from Products

select *from products 
where category='electronics'

--Display the 10 most expensive products.
select top 10 * from products 
order by list_price desc




--Find orders placed through the Mobile App.

select * from orders 

select * from orders 
where sales_channel='mobile app'


--Find deliveries where actual_delivery_days is greater than 7.

select * from Deliveries
where actual_delivery_days>7


--?? Aggregations — COUNT, SUM, AVG, MIN, MAX
--Find the total number of customers, products, sellers and orders.
select * from orders 

select count(distinct customer_id) as no_of_cust,
		count(distinct product_id) as no_of_prodct,
		count(distinct seller_id) as no_of_seller,
		count(distinct order_id) as no_of_orders
		from orders

--Calculate total revenue from all orders.
select * from orders 

select sum(net_sales) as revenue from orders

--Calculate total profit generated by the company.
select * from orders

select sum(profit) as profit from orders 


--Calculate the average order value.

select avg(net_sales) as avgval from orders


--Find the highest and lowest product prices.

select*from products

select max(list_price) as highest,
		min(list_price) as lowestprice from products

--Calculate the total quantity of products sold.

select sum(quantity) as qtysold from orders


--Find the average delivery time.
select *from orders
select * from Deliveries

SELECT AVG(actual_delivery_days) AS average_delivery_days
FROM Deliveries;
--Calculate the total discount amount given to customers.

select *from orders

select sum(discount_amount) as totaldis from orders



--Calculate the total shipping fees collected.
select * from orders 

select sum(shipping_fee) as total from orders


--Find the total sales and profit for each order status.

select *from orders 

select order_status,sum(net_sales) as totalsales,
		sum(profit) as totalprofit from orders
		group by order_status

--?? GROUP BY & HAVING
--Find total sales for each product category.
select * from Products
select * from orders 

select p.category,sum(o.net_sales) as totalsales from Products p 
join Orders o on o.product_id=p.product_id
group by p.category




--Find total profit for each region.
select * from orders 
select * from customers 

select c.region ,sum(o.profit) as totalprofit from orders o 
join Customers c on c.customer_id=o.customer_id
group by c.region



create procedure ord
as
begin
select * from orders
end 
ord
exec ord
--Find the number of orders for each sales channel.
select sales_channel,count(distinct order_id) as no_of_orders from orders
group by sales_channel

--Find the number of customers in each customer segment.

select * from customers 

select customer_segment,count(customer_id) as no_of_cust from customers 
group by customer_segment



--Find the average delivery time for each delivery partner.

select * from Deliveries

select delivery_partner,avg(actual_delivery_days) as avgdays from Deliveries
group by delivery_partner

--Find the top 10 sellers based on total sales.
ord

select top 10 seller_id,sum(net_sales) as totalsales from orders
group by seller_id
order by totalsales desc

--Find categories whose total sales are greater than ?1 crore.

select * from products 

select p.category,sum(net_sales) as totalsales from orders o 
join Products p on p.product_id=o.product_id
group by p.category
having sum(net_sales) >10000000;



--Find sellers who generated more than ?50 lakh in sales.

select seller_id,sum(net_sales) as totalsales from orders 
group by seller_id
having sum(net_sales)>5000000




--Find regions having more than 5,000 orders.

select c.region ,count(o.order_id) as orders from orders o
join customers c on c.customer_id=o.customer_id
group by c.region
having count(o.order_id)>5000


--Find the average product rating for each category.

select * from products 

select category,avg(product_rating) as avgrat from products 
group by category




--?? JOINs
--Display Order ID, Customer Name, Product Name, Seller Name and Net Sales.
ord
select * from customers 
select * from products 
select * from Sellers


select o.order_id,c.customer_name,p.product_name,s.seller_name,o.net_sales from orders o
join customers c on c.customer_id=o.customer_id
join products p on p.product_id=o.product_id
join Sellers s on s.seller_id=o.seller_id



--Find total sales generated by each customer.

select c.customer_id,c.customer_name,sum(o.net_sales) as totalsales from orders o 
join customers c on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name

--Find total sales generated by each product.

select p.product_id,p.product_name,sum(o.net_sales) as totalsales 
from orders o 
join Products p on p.product_id=o.product_id
group by  p.product_id,p.product_name





--Find total profit generated by each seller.


select s.seller_id,s.seller_name,sum(o.profit) as totalprofit from orders o 
join sellers s on s.seller_id=o.seller_id
group by s.seller_id,s.seller_name




--Find total sales by customer region.

select c.region ,sum(o.net_sales) as totalsales from orders o 
join customers  c on c.customer_id=o.customer_id
group by c.region

--Display Order ID, Customer Name, Payment Method and Payment Status.

select *from Payments
ord
select o.order_id,c.customer_name,p.payment_method,p.payment_status from orders o 
join customers c on c.customer_id=o.customer_id
join payments p on p.order_id=o.order_id

--Display Order ID, Customer Name, Delivery Partner and Delivery Status.
select o.order_id,c.customer_name,o.delivery_partner,d.delivery_status from orders o 
join customers c on c.customer_id=o.customer_id
join Deliveries d on d.order_id=o.order_id



--Find the top 10 customers based on total spending.
select top 10 c.customer_id,c.customer_name,sum(o.net_sales) as totalspent 
from orders o 
join Customers c on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by totalspent desc

--Find customers who have placed more than 10 orders.
select c.customer_id,c.customer_name,count(o.order_id) as orders from orders o 
join customers c on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
having count(o.order_id)>10

--Find products that have never been ordered.

select p.product_id,p.product_name,o.order_id from products p 
left join orders o on o.product_id=p.product_id
where o.order_id is null



--?? CASE, Date & Business Calculations
--Categorize customers into age groups: 18–25, 26–35, 36–50, 51+.

select * from customers 

select customer_id,customer_name,age,
		case 
			when age between 18 and 25 then 'young poragallu'
			when age between 26 and 35 then 'young'
			when age between 36 and 50 then 'old'
			else'musalollu'
		end
		from Customers



--Categorize orders based on net_sales as Low, Medium, High and Premium.

select* from products 

select p.category,sum(o.net_sales) as totalsales,
			case
				when sum(o.net_sales)>15000000 then'premium'
				when sum(o.net_sales)>1000000and sum(o.net_sales)<15000000 then'high'
				when sum(o.net_sales)<1000000and sum(o.net_sales)<5000000 then'high'
				else 'low'
			end as classify
from products p 
join orders o on o.product_id=p.product_id
group by p.category
			
--Calculate the profit margin percentage for every order.

select * from orders 

select order_id,estimated_cost,profit,(profit*100/estimated_cost) as 'profit%' from orders 


select order_id,estimated_cost,profit,(profit*100/estimated_cost) as 'profit%',
		case	
			when (profit*100/estimated_cost) >50 then 'high profit'
			when (profit*100/estimated_cost) <50 and (profit*100/estimated_cost) >30 then 'medium prof'
			when (profit*100/estimated_cost) >0 and (profit*100/estimated_cost) <30 then'nrml prof'
			else 'loss'
		end as profclass
from orders 

--Calculate the number of days between order_date and delivery_date using DATEDIFF().

select * from orders

select order_id,datediff(dd,order_date,delivery_date) as days from orders


--Find monthly total sales and profit.

select format(order_date,'yyyy_MM') as month ,sum(net_sales) as totalsales from orders 
group by format(order_date,'yyyy_MM')
order by format(order_date,'yyyy_MM')


--Find the number of orders placed in each year and month.

select year(order_date) as yer,month(order_date) as monthh,count(order_id) as orders from orders
group by month(order_date) ,year(order_date)
order by year(order_date),month(order_date)

--Calculate the cancellation percentage of total orders.

select * from orders 

SELECT 
    COUNT(order_id) AS total_orders,
    SUM(CASE 
            WHEN order_status = 'cancelled' THEN 1 
            ELSE 0 
        END) AS cancelled_orders,
    SUM(CASE 
            WHEN order_status = 'cancelled' THEN 1 
            ELSE 0 
        END) * 100.0 / COUNT(order_id) AS cancellation_percentage
FROM orders;




--Calculate the return percentage of total orders.

select * from orders 

select count(order_id)  as orders ,
	sum(case	
		when order_status='returned' then 1
		else 0
	end) as returnss,
	sum(case	
		when order_status='returned' then 1
		else 0
	end)*100/count(order_id) as percentagee from orders


--?? Advanced — CTE, Subqueries & Window Functions
--Find customers whose total spending is greater than the average customer spending.

select c.customer_id,c.customer_name,sum(net_sales) as totalspent from customers c
join orders o on o.customer_id=c.customer_id
group by c.customer_id,c.customer_name
having sum(net_sales)>(select avg(customer_total) from
												(
													select c.customer_id,avg(o.net_sales) as customer_total
													from orders o 
													join customers c on c.customer_id=o.customer_id
													group by c.customer_id
												) as cust_spent
						);





--Find the second-highest selling product.

with cte as (
select top 2 p.product_id,p.product_name,count(o.quantity) as total from orders o 
join Products p on p.product_id=o.product_id
group by p.product_id,p.product_name
order by total desc
)
select product_id,product_name ,total from cte
where total = (select min(total) from cte)


select min(total)as nth_high from (
select top 2 p.product_id,p.product_name,count(o.quantity) as total from orders o 
join Products p on p.product_id=o.product_id
group by p.product_id,p.product_name
order by total desc) as highest


--Rank all products based on total sales using RANK().

select p.product_id,p.product_name,sum(o.net_sales) as totalsales,
rank() over(order by sum(o.net_sales) desc) as rnk
from orders o 
join products p on p.product_id=o.product_id
group by p.product_id,p.product_name





--Find the Top 3 products in each category using a window function.

select * from products 

with cte as (
select p.category,p.product_name,sum(o.net_sales) as totalrev ,
dense_rank() over(partition by p.category order by sum(o.net_sales) desc) as rnk
from orders o 
join products p on p.product_id=o.product_id
group by p.category,p.product_name
)
select * from cte 
where rnk<=3;


--Calculate a running total of monthly sales using SUM() OVER().

select year(order_date)as yer,month(order_date) as monthh ,sum(net_sales) as sales,
sum(sum(net_sales)) over(partition by year(order_date) order by year(order_date),month(order_date)) as running
from orders 
group by year(order_date),month(order_date)


--Calculate month-over-month sales growth percentage using LAG().

select year(order_date) as yer,month(order_date) as monthh,

with cte as (
select year(order_date) as yer,month(order_date) as monthh,sum(net_sales) as sales,
lag(sum(net_sales)) over(partition by year(order_date) order by year(order_date),month(order_date)) as prev
from orders 
group by year(order_date),month(order_date)
)
select *,concat((round(((sales-prev)*100/prev),0)),'%') as percentt from cte


--Find the Top 3 customers in each region based on total spending.

with cte as (
select c.region ,c.customer_id,c.customer_name,sum(o.net_sales) as sales,
DENSE_RANK() over(partition by c.region order by sum(o.net_sales) desc) as rnk
from orders o 
join customers c on c.customer_id=o.customer_id
group by c.region ,c.customer_id,c.customer_name
)
select * from cte 
where rnk<=3



--Part A — Window Functions & Ranking
--1. Rank customers based on their total spending.

--Concepts: RANK(), SUM(), GROUP BY

--2. Rank products based on total sales.

--Concepts: RANK()

--3. Find the top 3 products in each category based on sales.

--Concepts: ROW_NUMBER() / RANK(), PARTITION BY

--4. Find the top 3 sellers in each region based on total sales.

--Concepts: PARTITION BY, ranking

--5. Calculate the running total of monthly sales.

--Concepts: SUM() OVER()

--6. Calculate month-over-month sales growth.

--Concepts: LAG(), CTE, date functions

--7. Find each customer's first and most recent order.

--Concepts: MIN(), MAX() / window functions

--Part B — Sales & Profit Analysis
--8. Calculate total revenue, total profit and overall profit margin.

select sum(net_sales) as totalrevenue,
		sum(profit) as totalprofit,
		((sum(net_sales)-sum(profit))*100/sum(net_sales)) as profitmargin
		from orders 

--9. Find monthly sales, profit and profit margin.

select year(order_date)as yer,month(order_date) as monthh,
		sum(net_sales) as sales,sum(profit) as totalprof,
		(sum(net_sales)-sum(profit))*100/sum(net_sales) as profmargin
		from orders 
		group by year(order_date),month(order_date)
		order by year(order_date),month(order_date)



--10. Find the top 10 products contributing the most revenue.

select top 10  p.product_id,p.product_name,sum(o.net_sales) as revenue from orders o
join products p on p.product_id=o.product_id
group by p.product_id,p.product_name
order by revenue desc


--11. Find categories with high sales but low profit margin.

select p.category,sum(o.net_sales) as sales,
		(sum(o.net_sales)-sum(o.profit))*100/sum(o.net_sales)  as margin 
		from orders o 
		join products p on p.product_id=o.product_id
	group by p.category
order by sum(o.net_sales) desc, margin asc




--12. Calculate each category's percentage contribution to total sales.

SELECT
    p.category,
    SUM(o.net_sales) AS category_sales,
    SUM(o.net_sales) * 100.0 /
        (SELECT SUM(net_sales) FROM Orders) AS sales_contribution_pct
FROM Orders o
JOIN Products p
    ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY sales_contribution_pct DESC;


--13. Find the month with the highest sales.
select year(order_date) as yer,
		month(order_date) as monthh,
		sum(net_sales) as sales 
		from orders o 
		group by  year(order_date),month(order_date)
		order by sales desc



--14. Find the month with the highest profit.

select year(order_date) as yer,
		month(order_date) as monthh,
		sum(profit) as profit 
		from orders o 
		group by  year(order_date),month(order_date)
		order by profit desc

--Part C — Customer Analysis
--15. Find the top 10 customers based on total spending.


select top 10 c.customer_id,c.customer_name,sum(o.net_sales) as totalspent from orders o 
join customers c on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
order by totalspent desc


--16. Find customers who placed more than 10 orders.

select c.customer_id,c.customer_name,count(o.order_id) as orders from orders o 
join customers c on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
having count(o.order_id)>10



--17. Calculate each customer's:
--Total Orders
--Total Sales
--Total Profit
--Average Order Value
select * from orders

select c.customer_id,c.customer_name,
		count(o.order_id) as orders,
		sum(o.net_sales) as sales ,
		sum(o.profit) as profit,
		avg(o.net_sales) as avgordervalue
		from orders o
		join customers c on c.customer_id=o.customer_id
		group by c.customer_id,c.customer_name





--18. Find customers who haven't placed an order in the last 90 days.

select c.customer_id,c.customer_name,max(o.order_Date)as lastorderdate from orders o 
join customers c on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name
having max(o.order_date)<dateadd(dd,-90,getdate())


--19. Find the percentage of total company revenue generated by the top 10 customers.

select top 10 c.customer_id,c.customer_name,sum(o.net_sales) as cust_sales,
		sum(o.net_sales)*100/
					(select sum(net_sales) from orders) as percentt
				from orders o 
				join customers c on c.customer_id=o.customer_id
				group by c.customer_id,c.customer_name
				order by percentt desc


WITH TopCustomers AS
(
    SELECT TOP 10
        c.customer_id,
        c.customer_name,
        SUM(o.net_sales) AS customer_sales
    FROM Orders o
    JOIN Customers c
        ON c.customer_id = o.customer_id
    GROUP BY
        c.customer_id,
        c.customer_name
    ORDER BY customer_sales DESC
)
SELECT
    SUM(customer_sales) AS top_10_sales,
    SUM(customer_sales) * 100.0 /
        (SELECT SUM(net_sales) FROM Orders) AS top_10_revenue_percentage
FROM TopCustomers;



--Part D — Product & Category Analysis
--20. Find the top 5 products within each category based on sales.

with cte as (
select p.category,p.product_id,p.product_name,sum(o.net_sales) as sales ,
DENSE_RANK() over(partition by p.category order by sum(o.net_sales) desc) as rnk 
from orders o 
join products p on p.product_id=o.product_id
group by p.category,p.product_id,p.product_name
)
select * from cte 
where rnk<=5

--21. Find products with high sales but below-average product ratings.

select * from products 
select * from orders 

select p.product_id,p.product_name,sum(o.net_sales) as sales,
avg(p.product_rating) as avgrat
from Products p
join orders o on o.product_id=p.product_id
group by p.product_id,p.product_name
order by sum(o.net_sales) desc ,avg(p.product_rating) asc



--22. Find the most profitable category.

select top 1 p.category ,sum(o.profit) as profit from orders o 
join products p on p.product_id=o.product_id
group by p.category
order by profit desc


--23. Find the category with the highest average discount.

select * from orders 

select top 1 p.category,avg(o.discount_amount) as avgdis from orders o 
join products p on p.product_id=o.product_id
group by p.category
order by AVGdis desc





--Part E — Seller Performance
--24. Create a seller performance report containing:
--Seller Name
--Total Orders
--Total Sales
--Total Profit
--Average Order Value
--Seller Rating
--Profit Margin

select * from sellers
select * from orders 

select s.seller_name,count(o.order_id) as orders,
					sum(o.net_sales) as totalsales,
					sum(o.profit) as totalprofit,
					avg(o.net_sales) as avgval,
					s.seller_rating ,
					sum(o.profit)*100/sum(net_sales) as profmrgn
					from orders o 
					join sellers s on s.seller_id=o.seller_id
			group by s.seller_id,s.seller_name,s.seller_rating


--25. Identify sellers whose sales are above average but whose profit margin is below average.

select s.seller_id,s.seller_name,sum(o.net_sales) as sales
from orders o 
join sellers s on s.seller_id=o.seller_id
group by s.seller_id,s.seller_name
having sum(o.net_sales) >(select avg(net_sales) from orders) 
order by sales 



WITH SellerPerformance AS
(
    SELECT
        s.seller_id,
        s.seller_name,
        SUM(o.net_sales) AS total_sales,
        SUM(o.profit) AS total_profit,
        SUM(o.profit) * 100.0 /
            NULLIF(SUM(o.net_sales), 0) AS profit_margin
    FROM Orders o
    JOIN Sellers s
        ON s.seller_id = o.seller_id
    GROUP BY
        s.seller_id,
        s.seller_name
)
SELECT
    seller_id,
    seller_name,
    total_sales,
    total_profit,
    profit_margin
FROM SellerPerformance
WHERE total_sales > (SELECT AVG(total_sales) FROM SellerPerformance)
  AND profit_margin < (SELECT AVG(profit_margin) FROM SellerPerformance)
ORDER BY total_sales DESC;


--Part F — Delivery Performance
--We'll then do these separately because delivery analysis is a major part of this project:

--26. Calculate overall on-time delivery percentage.

select * from orders 
select * from Deliveries

with cte as (
select sum(case
				when promised_delivery_date = actual_delivery_date then 1 
				else 0
			end ) as no_of_ontime_dd,
			count(actual_delivery_date) as totaldays
			from Deliveries
			)
			select (no_of_ontime_dd*100/totaldays) as percnt from cte
		

--27. Find average delivery days for each delivery partner.

select* from Deliveries

select delivery_partner,avg(actual_delivery_days) as avgdays from Deliveries
group by delivery_partner


--28. Find the delivery partner with the highest delay rate.

SELECT TOP 1
    delivery_partner,
    SUM(
        CASE
            WHEN actual_delivery_date > promised_delivery_date
            THEN 1
            ELSE 0
        END
    ) * 100.0 / COUNT(*) AS delay_rate
FROM Deliveries
GROUP BY delivery_partner
ORDER BY delay_rate DESC;


--29. Find regions with above-average delivery delays.

select*from Deliveries
select * from customers

with cte as (
select c.region ,sum( CASE
						WHEN d.actual_delivery_date > d.promised_delivery_date
						THEN 1
						ELSE 0
					END) as delays
					from customers c  
					join orders o on o.customer_id=c.customer_id
					join Deliveries d on d.order_id=o.order_id
					group by c.region
	)
	select region ,delays from cte 
	where delays >(select avg(delays) from cte )



--30. Analyze the relationship between delivery distance and delivery time.
SELECT
    CASE
        WHEN distance_km < 100 THEN '0-100 km'
        WHEN distance_km < 500 THEN '100-500 km'
        WHEN distance_km < 1000 THEN '500-1000 km'
        WHEN distance_km < 1500 THEN '1000-1500 km'
        WHEN distance_km < 2000 THEN '1500-2000 km'
        ELSE '2000+ km'
    END AS distance_range,
    
    COUNT(*) AS total_deliveries,
    AVG(actual_delivery_days) AS avg_delivery_days
FROM Deliveries
GROUP BY
    CASE
        WHEN distance_km < 100 THEN '0-100 km'
        WHEN distance_km < 500 THEN '100-500 km'
        WHEN distance_km < 1000 THEN '500-1000 km'
        WHEN distance_km < 1500 THEN '1000-1500 km'
        WHEN distance_km < 2000 THEN '1500-2000 km'
        ELSE '2000+ km'
    END
ORDER BY
    MIN(distance_km);

--Part G — Payment Analysis
--31. Find the number of transactions for each payment method.

select * from payments 

select payment_method,count(payment_id) as no_Of_pmt from payments 
group by payment_method


--32. Find total sales by payment method.

select p.payment_method,sum(o.net_sales) as sales from orders o 
join payments p on p.order_id=o.order_id
group by p.payment_method

--33. Find payment failure percentage for each payment method.

select * from payments 


with cte as (
select payment_method, count(payment_status) as total,
							sum(case
								when payment_status ='failed' then 1 
								else 0
							end) as faildpaymnts
							from payments p 
							group by payment_method
			)
			select payment_method,((faildpaymnts*100)/total) as failedpercent from cte 


--34. Find the payment method generating the highest transaction fees.

select * from payments 

select top 1 payment_method ,sum(transaction_fee) as fee from payments 
group by payment_method
order by fee desc


--Part H — SQL Views for Power BI

--This is the most important part before Excel/Power BI.

--Instead of sending all raw tables directly into Power BI, we'll create useful SQL views.

--For example:

--View 1 — Sales Analysis
--vw_SalesAnalysis

--Containing:

--Order ID
--Order Date
--Customer
--Product
--Category
--Brand
--Seller
--Region
--Quantity
--Gross Sales
--Discount
--Net Sales
--Profit
--Profit Margin
--Sales Channel
select * from  products 
select * from orders 
select * from sellers 

create or alter view vw_SalesAnalysis
as 
select o.order_id,o.order_date,c.customer_name,p.product_name,p.category,
		p.brand,s.seller_name,c.region ,o.quantity ,o.gross_sales ,
		sum(o.discount_amount) as discount,o.net_sales  ,o.profit  ,
		((sum(o.profit) *100)/sum(o.net_sales)) as profitmrgn,o.sales_channel 
		from orders o 
		join products p on  p.product_id=o.product_id
		join Sellers s on s.seller_id=o.seller_id
		join customers c on c.customer_id=o.customer_id
		group by o.order_id,o.order_date,c.customer_name,p.product_name,p.category,
		p.brand,s.seller_name,c.region,o.sales_channel,o.quantity,o.gross_sales,o.net_sales,o.profit

select * from vw_SalesAnalysis


--View 2 — Customer Analysis
--vw_CustomerAnalysis

--Containing:

--Customer
--Region
--Customer Segment
--Total Orders
--Total Sales
--Total Profit
--Average Order Value

create or alter view vw_CustomerAnalysis
as
select c.customer_name,c.region,c.customer_segment,count(distinct o.order_id) as orders ,
		sum(o.net_sales) as sales,sum(o.profit)as profit ,
		sum(o.net_sales)/count(distinct o.order_id) as avgval
		from orders o 
		join customers c on c.customer_id=o.customer_id
		group by c.customer_id,c.customer_name,c.region,c.customer_segment


select *from vw_CustomerAnalysis


--View 3 — Product Analysis
--vw_ProductAnalysis

--Containing:

--Product
--Category
--Brand
--Orders
--Quantity Sold
--Sales
--Profit
--Profit Margin
--Rating

create view vw_ProductAnalysis
as 
select p.product_name,p.category,p.brand,count(distinct o.order_id) as orders,sum(o.quantity) as soldqty,
				sum(o.net_sales) as sales,sum(o.profit) as profit,
				((sum(o.profit)*100)/sum(o.net_sales)) as mrgn,p.product_rating from products p 
				join orders o on o.product_id=p.product_id
				group by p.product_name,p.category,p.brand,p.product_rating


select * from vw_ProductAnalysis


--View 4 — Seller Performance
--vw_SellerPerformance

--Containing:

--Seller
--Orders
--Sales
--Profit
--Profit Margin
--Seller Rating

select * from sellers



create view vw_SellerPerformance
as 
select s.seller_name,count(distinct o.order_id) as orders ,
		sum(o.net_sales) as sales,sum(o.profit) as profit,
		((sum(o.profit)*100)/sum(o.net_sales)) as mrgn,
		s.seller_rating from sellers s 
		join orders o on o.seller_id=s.seller_id
		group by s.seller_name,s.seller_rating


select * from vw_SellerPerformance


--View 5 — Delivery Performance
--vw_DeliveryPerformance

--Containing:

--Order ID
--Region
--Delivery Partner
--Promised Days
--Actual Days
--Delay Days
--Delivery Status
--Delivery Cost
--Distance

select * from orders 
select * from Deliveries
select * from customers 

create view vw_DeliveryPerformance
as 
select o.order_id,c.region ,d.delivery_partner,d.promised_days,d.actual_delivery_days,
			(convert(int,d.actual_delivery_days))-(convert(bigint,d.promised_days)) as delaydays,
				d.delivery_status,d.delivery_cost,d.distance_km from orders o 
				join Deliveries d on d.order_id=o.order_id
				join customers c on c.customer_id=o.customer_id


select * from vw_DeliveryPerformance



--View 6 — Payment Analysis
--VW_PAYMENTANALYSIS

--Containing:

--Payment Method
--Payment Status
--Transactions
--Amount Paid
--Transaction Fees

CREATE VIEW VW_PAYMENTANALYSIS
AS
SELECT
    p.payment_method,
    p.payment_status,
    COUNT(DISTINCT p.order_id) AS transactions,
    SUM(p.amount_paid) AS amount_paid,
    SUM(p.transaction_fee) AS transaction_fees
FROM payments p
JOIN orders o
    ON o.order_id = p.order_id
GROUP BY
    p.payment_method,
    p.payment_status;


select * from VW_PAYMENTANALYSIS


--These views will make the transition to Power BI much cleaner.